# Generated by Django 4.1.3 on 2026-01-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("enseignant", "Enseignant"),
                    ("etudiant", "Étudiant"),
                ],
                default="etudiant",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
