# Generated by Django 4.1.3 on 2026-01-31 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'objet est actif ou non",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: CP, CE1, 6th, Terminale, L1",
                        max_length=50,
                        verbose_name="Class name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'objet est actif ou non",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("exam", "Exam"),
                            ("correction", "Correction"),
                        ],
                        max_length=20,
                        verbose_name="Content type",
                    ),
                ),
                ("youtube_url", models.URLField(verbose_name="YouTube link")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Contents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'objet est actif ou non",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: Primary, Secondary, Higher",
                        max_length=50,
                        unique=True,
                        verbose_name="Level name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Level description",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Level",
                "verbose_name_plural": "Levels",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'objet est actif ou non",
                        verbose_name="Actif",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("youtube_link", models.URLField(verbose_name="YouTube link")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        help_text="Related educational content",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="education.content",
                        verbose_name="Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'objet est actif ou non",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: Mathematics, French",
                        max_length=100,
                        verbose_name="Subject name",
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="education.classlevel",
                        verbose_name="Class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["id"],
                "unique_together": {("class_level", "name")},
            },
        ),
        migrations.AddField(
            model_name="content",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="education.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'objet est actif ou non",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="Author name"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="education.content",
                        verbose_name="Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="classlevel",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="education.level",
                verbose_name="Level",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classlevel",
            unique_together={("level", "name")},
        ),
    ]
